### ISSUE TITLE
JavaScript ou TypeScript?

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#1]
Quel langage de programmation utiliser pour le bot?

**Comment by targos** [comment]
Je suis d'avis de le faire en JS (en documentant bien les fonctions avec JSDoc) afin de ne pas laisser de coté les membres qui voudraient contribuer et ne connaissent pas TS.

**Comment by Sebastien-Ahkrin** [comment]
Perso je suis aussi de cet avis, le typescript c'est bien pratique mais trop de monde serait (à mon avis) sur le côté du style que pas tout le monde connait le typescript (moi y compris kappa) après à voir p-e avec un "sondage" avec tout les membres ?

**Comment by Xstoudi** [comment]
Je pense que peu importe si l'on utilise JS ou TS, le JSDoc sera de rigueur.
Pour moi on peu partir sur JS.

**Comment by Xstoudi** [comment]
Je pense que peu importe si l'on utilise JS ou TS, le JSDoc sera de rigueur.
Pour moi on peut partir sur JS.

**Comment by Purexo** [comment]
J'ai une très grosse préférence pour du ts.
J'arrive jamais à mes fin avec de la jsdoc et l'autocompletion est minable par rapport à ce qu'offre ts.

**Comment by Kawacrepe** [comment]
La question que j'aurai c'est, "avons nous réellement des membres n'utilisant pas le typescript || ne voulant pas l'apprendre ? Et si c'est le cas, ne serait-ce pas justement une bonne occasion pour l'apprendre ? Car on peut supposer qu'il sera aisé de discuter des choix qui seront fait et ainsi permettre à tout le monde de monter en compétence ?

**Comment by fraxken** [comment]
Je suis ok avec JavaScript + JSDoc.

**Comment by targos** [comment]
Faisons un petit sondage: https://www.strawpoll.me/21109936

**Comment by targos** [comment]
Le projet a démarré en TypeScript
