### ISSUE TITLE
Channel Liens

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [ES-Community/bot#2]
une idée qui pourrait être intéressant c'est d'avoir une commande qui démarre un "tool" en message privée et qui nous permettrais de faire un message dans lien (il serait envoyé par le bot) qui respecterais exactement les "lignes de conduites" pré-définie

ça pourrait être une succession de message comme une "conversation" entre le bot et l'utilisateur

Vous en pensez quoi ?

**Comment by targos** [comment]
Dans le cas où quelqu'un poste un message mal formaté, le bot pourrait démarrer une conversation pour le corriger. A la fin le message serait remplacé.

**Comment by Mesteery** [comment]
Je suis d'accord avec ton idée targos, c'est plus pratique que d'exécuter la commande, ça fais gagner du temps et ça n'oblige pas de passer par la commande

**Comment by Mesteery** [comment]
https://github.com/ES-Community/bot/pull/18 est merge, on peut close ?
