### ISSUE TITLE
Validation lors de l'arrivé sur ES-Community

### ISSUE THREAD

**Issue by DraftProducts** [ES-Community/bot#20]
Dans le but de simplifier la validation d'un membre au sein de la communauté lors de son arrivée, je penses que ça serait intéressant d'avoir un salon réservé aux nouveaux membres et aux administrateurs.
Lors de l'envoi d'un message, si le message se trouve dans le salon présentation et qu'il a une taille minimum défini par les admins.
Il recevrait une ou deux réaction(s) et l'interaction avec cette dernière de la part d'un admin permettrait de valider ou voter pour l'acceptation du membre en question. 
Une fois une décision prise à l'aide de la ou les réaction(s) le contenu du message serait supprimé et envoyé par le bot dans un salon publique de présentations sous cette forme: 

![image](https://user-images.githubusercontent.com/29425008/98852676-5105f900-2458-11eb-89cf-484003604f75.png)

**Comment by Mesteery** [comment]
Je pense que c'est useless
Dans tous les cas il faut la validation d'un admin.
L'idée là c'est juste un salon supplémentaire seulement visible par le nouveau et les admins, le message est renvoyé dans le salon #presentation si c'est accepté. Je vois pas trop l'intérêt. Et que ce passe-t-il si c'est refusé ?

**Comment by DraftProducts** [comment]
Pas forcément besoin de refuser, si on ne met qu'une réaction comme 👌 qui est déjà utilisé dans le salon présentation je penses que ça pourrait suffire.
A l'heure actuelle les admins doivent modifier les rôles du membre ne question, ça permettrait juste de rendre la chose plus simple ou comme je l'ai expliqué plus haut de le faire valider par plus d'une personne.

**Comment by Xstoudi** [comment]
L'autre idée à laquelle on avait réfléchi c'est que le bot entame une conversation avec l'arrivant pour préparer une présentation un minimum complète. La grosse limite de cela c'est que le bot peut ne pas réussir à envoyer un message aux gens, en fonction de leurs paramètres de confidentialité.
Je pense que ta solution est meilleure, perso c'est un +1.

**Comment by targos** [comment]
Sur le discord de Kent c dodds, pour éviter le problème de la confidentialité, le bot crée un channel temporaire ou seul lui et le nouveau membre ont les droits d'accès pour faire la discussion.
Je ne pense pas que ça vaut forcément la peine, mais je voulais mentionner la possibilité^^

**Comment by Mesteery** [comment]
De ce que j'ai compris c'est justement ça son idée, de créer un salon temporaire

**Comment by DraftProducts** [comment]
Non, il ne faut pas oublier qu'il y a deux limites de salons sur les serveurs discord, la première de 500 qui est pour le serveur complet. Celle qui nous gênerais avec ce système c'est celle qui nous limite à 50 salons par catégorie.
D'autres part ça m'étonnerais que ce soit agréable pour les admins d'avoir une catégorie de 50 salons sur le serveur.

L'idée était de n'avoir qu'un seul salon pour tout le monde.
En plus il me semble que le serveur de @DeltaEvo fonctionnait comme ça 🤔

**Comment by RomainLanz** [comment]
Je ne vois pas de soucis de créer un salon temporaire, si la personne ne fait pas de présentation en 5 jours, il est kick du serveur et son salon est supprimé.

**Comment by DraftProducts** [comment]
A vous de voir ce qui vous arrange, je sais que personnellement ça me dérangerait d'avoir des salons supplémentaires pour ça.
A voir en fonction du taux d'engagements des nouveaux arrivant.
