### ISSUE TITLE
Channel jobs

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [ES-Community/bot#3]
Même chose que pour #2 on pourrait avoir une "discussion" avec le bot afin de créer un message dans jobs ?

**Comment by Mesteery** [comment]
> Dans le cas où quelqu'un poste un message mal formaté, le bot pourrait démarrer une conversation pour le corriger. A la fin le message serait remplacé.

_Originally posted by @targos in https://github.com/ES-Community/bot/issue_comments/711127524_

Je pense que c'est aussi valable ici ?

**Comment by Mesteery** [comment]
https://github.com/ES-Community/bot/pull/18 est merge, on peut close ?
