### ISSUE TITLE
Planification: refacto cron de Epic et GoG pour stocker les dernières promo trouvé

### ISSUE THREAD

**Issue by Purexo** [ES-Community/bot#52]
Afin de comparer à la prochaine itération les résultats et savoir si on doit les afficher.

Prérequis :
1. PR https://github.com/ES-Community/bot/pull/51 mergé
2. PR https://github.com/ES-Community/bot/pull/50 mergé
3. host docker avec volume

---

Utiliser le KeyValue sqlite data store pour comparer les derniers jeux gratuits. Une clé par provider

**Comment by targos** [comment]
@Purexo Il reste qch à faire après https://github.com/ES-Community/bot/pull/59 ?

**Comment by Purexo** [comment]
Nope je close
