### ISSUE TITLE
Deux bots (staging et production)?

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#6]
Je n'ai jamais développé de bot Discord. Si nous voulons avoir un déploiement staging automatique au niveau du serveur de test et un autre déploiement en production sur le serveur ESC, faut-il créer deux bots séparés?

**Comment by Xstoudi** [comment]
Oui

**Comment by Mesteery** [comment]
Je pense que oui, en tout cas, c'est ce que je fais moi et je pense que c'est la manière la plus simple et pratique.

**Comment by targos** [comment]
OK, c'est fait.
