### ISSUE TITLE
Message du bot à l'ouverture d'un fil dans un channel ou il vérifie le formatage du message

### ISSUE THREAD

**Issue by Purexo** [ES-Community/bot#60]
![image](https://user-images.githubusercontent.com/5005154/193574499-095b4c72-be37-4d7d-a97c-fb821be9960c.png)

J'ai ouvert le thread `State of CSS 2022` dans #liens et le bot m'a retourné le message ci-dessus (sans pouvoir effacer le thread, ouf ^^)

**Comment by targos** [comment]
Fix: https://github.com/ES-Community/bot/pull/61
