### ISSUE TITLE
Comment permettre de tester le code avant de le déployer?

### ISSUE THREAD

**Issue by targos** [ES-Community/bot#7]
Il est clair que partager la clé du bot avec beaucoup de monde n'est pas une solution, rien que pour des raisons de sécurité. Du coup, comment faire pour qu'un contributeur puisse tester son code avant de le proposer?

**Comment by Mesteery** [comment]
Partager la clé du bot aux contributeurs "de confiances".
Proposer le lien du modèle (du serveur `ESC Bot Tesing`) pour que le reste des contributeurs puissent créer leur propre serveur et puissent inviter leur propre bot ESC.

**Comment by Xstoudi** [comment]
Le lien du template me paraît plus approprié que la distribution de la clé.

**Comment by targos** [comment]
Ok j'ai créé un lien vers le template du serveur de test. Je vais laisser ce ticket ouvert quelques jours au cas où quelqu'un aurait une autre idée.
