### ISSUE TITLE
Ajout des comics Work Chronicles

### ISSUE THREAD

**Issue by antoineneff** [ES-Community/bot#85]
### Suggestion

Avoir les nouveaux comics de Work Chronicles publiés automatiquement dans le channel `#gif`

### Détails

Site web: https://workchronicles.com
API: https://workchronicles.com/wp-json/wp/v2/posts

### Exemple de post

![](https://workchronicles.com/wp-content/uploads/2023/09/Memory-Error.png)

**Comment by Purexo** [comment]
Ça me semble un bon strip à ajouter.
Si tu en as le temps et l'envie, tu peux toi même t'en occuper en t'inspirant de https://github.com/ES-Community/bot/blob/main/src/crons/CommitStrip.ts qui utilise la même api wordpress si je ne m'abuse
